# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplierChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('previous_multiplier', models.FloatField()),
                ('current_multiplier', models.FloatField()),
                ('cause', models.CharField(choices=[('User action', 'User action'), ('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('amount', models.FloatField()),
                ('multiplier', models.FloatField(default=1.0)),
                ('initial_multiplier', models.FloatField(default=1.0)),
                ('users', models.ManyToManyField(related_name='projects_supported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectSupportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_multiplier', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_users_log', to='predict.ProjectProposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_supported_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='multiplierchangelog',
            name='related_log',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.UserProjectSupportLog'),
        ),
    ]
