# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects_supported', to=settings.AUTH_USER_MODEL),
        ),
    ]
