# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0002_auto_20160418_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='users',
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='challenge',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='impact',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='impact_indicators',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='logo',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='outcomes',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='outcomes_indicators',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='output',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='output_indicators',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='picture',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='proposal',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supporting_users',
            field=models.ManyToManyField(blank=True, related_name='projects_supported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
