# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0003_auto_20160419_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='logo',
            field=models.ImageField(upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='picture',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
